# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for a full reference

name: Metrics

on:
  schedule: [{cron: "0 0 */10 * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: pirmax
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_lines: yes
          plugin_stargazers: yes
